import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scrollbar-hide" lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}




// 'use client'
// import { useEffect } from 'react';
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import ClientProvider from "./ClientProvider";
// import 'focus-visible';

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   useEffect(() => {
//     // Add js-focus-visible class to the html element on the client side
//     document.documentElement.classList.add('js-focus-visible');
//   }, []);

//   return (
//     <html className="scrollbar-hide" lang="en">
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <ClientProvider>
//           {children}
//         </ClientProvider>
//       </body>
//     </html>
//   );
// }





